Rework taglist
alicekore/Meet-and-Eat pull request #140
Opened 2019-07-03 10:09 UTC by Lewandowski516

![image](https://user-images.githubusercontent.com/49785134/60583485-5135b500-9d8b-11e9-807a-033653712663.png)
![image](https://user-images.githubusercontent.com/49785134/60583528-64488500-9d8b-11e9-87a6-c784e0fd82d2.png)

2019-07-03 12:47 UTC, niwie requested changes
Space between create event und dropdown appears to be to small. 
--> increase space 
after changing add new screenshot pls

2019-07-04 16:17 UTC, hobergma submitted a review, later dismissed

2019-07-04 22:37 UTC, niwie approved these changes

2019-07-05 13:25 UTC, alicekore approved these changes

2019-07-05 13:25 UTC, merged